### ISSUE TITLE
No "Convex Hull V-HACD" option from search results?

### ISSUE THREAD

**Issue by ethanjyx** [andyp123/blender_vhacd#11]
Hi there,

there is no "Convex Hull V-HACD" option for me when I try to search for it.
<img width="737" alt="Screen Shot 2021-02-02 at 3 09 00 PM" src="https://user-images.githubusercontent.com/3280308/106675386-e69dba00-6569-11eb-8a3c-0d7fbd140bb8.png">

I believe I should have installed it correctly.
<img width="734" alt="Screen Shot 2021-02-02 at 3 17 03 PM" src="https://user-images.githubusercontent.com/3280308/106675422-f1584f00-6569-11eb-912d-955844b8a1ea.png">

I'm using Mac, with blender 2.9.x,

what could be wrong here?

**Comment by Weisl** [comment]
Try searching for hacd. And if that does not solve the issue, enable  Developer extras in Preferences -> Interface. 
![image](https://user-images.githubusercontent.com/6353016/106676411-86d1fe00-65bf-11eb-90e3-a1cc6eddabbd.png)

**Comment by Weisl** [comment]
This setting :) 
![devextra](https://user-images.githubusercontent.com/6353016/106676586-de706980-65bf-11eb-9649-8d04ac9179fe.png)

**Comment by ethanjyx** [comment]
Thanks, enabling "Developer Extras" solved the issue
