### ISSUE TITLE
blender_2.92.0_vhacd can't run

### ISSUE THREAD

**Issue by king40168** [andyp123/blender_vhacd#12]
it seems that this plugin does not work. After importing the model, the plugin does not seem to work (maybe my plugin is not set well, but I do not know what the problem is).
Windows10 with Blender v 2.92.0 (also tied blender v2.80)

![image](https://user-images.githubusercontent.com/58094699/110227696-1c054100-7f36-11eb-8ac2-02bc59ed0c81.png)

**Comment by ghost** [comment]
I have the same issue. Can't see the context menu of the plugin (Blender 2.92, MacOS)

**Comment by king40168** [comment]
> I have the same issue. Can't see the context menu of the plugin (Blender 2.92, MacOS)

Maybe I have found the method, operation steps: press "N", select the tool, then select the plug-in of VHACD, open the plug-in, select your model, press "F3", enter V-hacd to search for the plug-in you want to call, and then select the parameters, and that's it

**Comment by Stinger05189** [comment]
> > I have the same issue. Can't see the context menu of the plugin (Blender 2.92, MacOS)
> 
> Maybe I have found the method, operation steps: press "N", select the tool, then select the plug-in of VHACD, open the plug-in, select your model, press "F3", enter V-hacd to search for the plug-in you want to call, and then select the parameters, and that's it
 
![image](https://user-images.githubusercontent.com/33469333/119161585-1c828380-ba1f-11eb-9103-977d3dd5d51e.png)

I believe I'm having the same issue. Plugin is not working at all.

**Comment by tpdickso** [comment]
If your issue is that you aren't able to find the operator in the menu, then https://github.com/andyp123/blender_vhacd/pull/8 will fix your issue. Unfortunately it looks like this repo isn't maintained so you may have to pull directly from the branch.

**Comment by andyp123** [comment]
I've merged in your pull request now @tpdickso , so thanks to you, this issue should be fixed. Custom operators always show up in my search menu (perhaps due to some setting somewhere) so I never noticed it wasn't accessible. Thanks for the help.
