### ISSUE TITLE
No meshes to process error on MacOS

### ISSUE THREAD

**Issue by jborbik** [andyp123/blender_vhacd#2]
Unfortunately I am unable to use the plugin with MacOS. I get only the orange error: "No meshes to process". I have followed the instruction in this repository.

<img width="202" alt="Bildschirmfoto 2019-10-05 um 14 30 13" src="https://user-images.githubusercontent.com/14967831/66254878-f2624c00-e77c-11e9-91de-0b585242d674.png">

I tried the decomposition of the same mesh **under Windows and there was no problem**.
Is there anything else I can do to make this issue more tractable?

**Comment by DmitryNeverov** [comment]
The solution that helped my case was to build the binaries myself with the following:
```
mkdir build && cd build
cmake ../src/
make
```
Then the executable for add-on will be `build/test/testVHACD`

**Comment by jborbik** [comment]
That helped, thanks a lot!
