### ISSUE TITLE
probably n00b question 

### ISSUE THREAD

**Issue by Juris3D** [andyp123/blender_vhacd#4]
Hello. Thank you for add-on! I am trying to get it into current 2.8x . Am i doing something wrong? Maybe i look in wrong place? I have it installed, and exe path added, but there is no entry in "Object" menu for selected object (i attach screens). What us my mistake here, please? :) 
Thank you.
EDIT: i am getting it thru F3 menu, and it is working. So, kind of "never mind" my question :) It works.
![screen1](https://user-images.githubusercontent.com/22710072/72665967-31f43180-3a16-11ea-85cb-f47fa223c929.jpg)
![screen2](https://user-images.githubusercontent.com/22710072/72665968-31f43180-3a16-11ea-85b2-e4245bf87ebf.jpg)

**Comment by binitshah** [comment]
Type `F3` to open up the Blender Operator Search Menu and start typing "Convex Hull" to find the operator.
